[toolchain]

[features]
resolution = true
skip-lint = false

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[programs.localnet]
mp_sol_restaking = "MVPpyLcH42bRtLXUWFnozcycqZ1WByvjDthCAgHh1fM"

[test.validator]
url = "https://api.mainnet-beta.solana.com"     # This is the url of the cluster that accounts are cloned from (See `test.validator.clone`).
ledger = "test-ledger"                          # Set ledger location.

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # implicitly also clones PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT

[[test.validator.clone]]
address = "wsoGmxQLSvwWpuaidCApxN5kEowLe2HLQLJhCQnj4bE" # sanctum-wSOL-SOL-Value-Calculator-Program

